# This example config is for a Microsoft Surface RT.


# Monitor usage of the network interface named `mlan0`
networks = [
	"mlan0",
]


# Sensors are read using the hwmon sysfs interface. Every hwmon device has a corresponding device name.
# So define some hwmon devices corresponding to the device names.
#
# Each entry here corresponds to a path under `/sys/class/hwmon`. The `dev_name` is the value of `/sys/class/hwmon/hwmon*/name`
[hwmon]
soc = { dev_name = "nct1008" }


# The battery of this device is not exposed as an hwmon device node, only as a power_supply device node.
#
# Each entry here corresponds to a path under `/sys/class/power_supply`. The value is the name of the directory.
[power_supply]
bat = "surface-rt-battery"


# List of sensor groups. Each group has a name, zero or more temp sensors, zero or more fan sensors, and zero or more battery sensors.
#
# Sensor groups allow you to group sensors from multiple hwmon devices into one logical group.
[[sensor]]
name = "SoC"
temps = [
	# These are temp sensors under the hwmon named "soc" and are temp sensor numbers 1 and 2 in that device.
	# For example, if that device had the path `/sys/class/hwmon/hwmon0`, then this sensor's values are read from
	# `/sys/class/hwmon/hwmon0/temp1_input` and `/sys/class/hwmon/hwmon0/temp2_input` respectively.
	{ hwmon = "soc", num = 1 },
	{ hwmon = "soc", num = 2 },
]

# The second sensor group is for the battery.
[[sensor]]
name = "Bat"
bats = [
	# This is a battery capacity sensor in the power_supply named "bat".
	#
	# That device had the path `/sys/class/power_supply/surface-rt-battery`, so this sensor's value is read from
	# `/sys/class/power_supply/surface-rt-battery/capacity`
	{ power_supply = "bat" },
]
