[package]
name = "sensord-common"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
dbus-pure-macros = { git = "https://github.com/Arnavion/dbus-pure", branch = "master" }
dbus-pure-proto = { git = "https://github.com/Arnavion/dbus-pure", branch = "master" }
serde = "1"
serde_derive = "1"
